Repository ByteCorum/DragonBurn, pull requests merged in 2025-09, with the labels that each got.

#222 docs: added templates for issues
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: docs

#227 style: removed spaces in auto-reply
  .github/workflows/issues-reply.yml
  .github/workflows/prs-reply.yml
Labels: low-priority, minor, style

#229 fix: menu toggle
  DragonBurn/Config/ConfigMenu.cpp
  DragonBurn/Config/ConfigSaver.cpp
  DragonBurn/Core/Cheats.cpp
  DragonBurn/Core/Config.h
  DragonBurn/Core/GUI.h
  DragonBurn/Core/Init.h
  DragonBurn/Resources/Language.hpp
Labels: high-priority, minor, fix

#239 docs: update to-do list
  docs/Todo.md
Labels: docs, no-priority, minor

#245 chore: added chore to pr options
  .github/pull_request_template.md
Labels: chore, low-priority, minor

#251 fix: #249
  DragonBurn/Features/Misc.cpp
Labels: low-priority, minor, fix, wip-status

#252 fix: `HumanizationStrength` and humanization jitter
  DragonBurn/Config/ConfigMenu.cpp
  DragonBurn/Config/ConfigSaver.cpp
  DragonBurn/Core/GUI.h
  DragonBurn/Features/Aimbot.cpp
  DragonBurn/Features/Aimbot.h
Labels: high-priority, minor, fix, wip-status

#254 fix: rcs
  DragonBurn/Features/RCS.cpp
Labels: minor, fix, medium-priority

#255 fix: Move EnemySound config from MiscCFG to ESPConfig
  DragonBurn/Config/ConfigMenu.cpp
  DragonBurn/Config/ConfigSaver.cpp
  DragonBurn/Core/Cheats.cpp
  DragonBurn/Core/Config.h
  DragonBurn/Core/GUI.h
  DragonBurn/Features/SoundESP.h
Labels: low-priority, minor, fix

#257 refactor: CMakeLists for DragonBurn
  CMakeLists.txt
Labels: low-priority, refactor, regular
